name: Release
on:
  push:
    branches: [ main ]
jobs:
  call-workflow-compiling-assets:
     uses: ./.github/workflows/action.yaml
  release:
    needs: call-workflow-compiling-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zephyr-artifacts
          path: |
              build/zephyr/zmk.hex
              build/zephyr/zmk.uf2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
