name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./.github/workflows/build.yml
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
